version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
  - package-ecosystem: "terraform"
    directory: "/examples/key-pair"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
